baseURL = "https://moshthesubnet.com"
theme = "congo"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
enableInlineShortcodes = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
    title = true

[permalinks]
  blog = "/blog/:contentbasename/"
