images = ["/img/concert-logo.png"]
colorScheme = "minimal"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = ["blog"]

[header]
  layout = "basic"
  showTitle = true

[homepage]
  layout = "custom"

[article]
  showDate = true
  showDateUpdated = false
  showReadingTime = false
  showTableOfContents = true
  showAuthor = false
  mermaid = true

[list]
  showSummary = true
  groupByYear = false

[footer]
  showCopyright = true
  showThemeAttribution = false
